AWSTemplateFormatVersion: 2010-09-09
Description: create EC2 instance for Nginx Puma(Rails)
#Metadata: 
#Mappings: 
#Conditions: 

Parameters: 
  SystemName:
    Description: What do you plan to name this system ?(e.g. WebSystem)
    Type: String
  
  Environment:
    Description: what environment will it be used(you can choose one) ?
    Type: String
    AllowedValues:
      - prod
      - test
      - dev

  InstanceType1:  
    Description: instance type for development
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large

  SubnetId1:
   Type: AWS::EC2::Subnet::Id #スタック作成時に既存サブネットを選択

  KeyName1: #既存キーペアから選択
    Description : Name of an existing EC2 KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
                  
  ImageId1:  #スタック作成時にSSMパラメータストアからAmazon Linux2の最新AMIのIDを取得
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  SecurityGroupId1:
    Type: List<AWS::EC2::SecurityGroup::Id>

Resources:
  IAMRoleForEC2: # EC2用のIAMロールを作成
    Type: AWS::IAM::Role
    Properties:
      RoleName: SecretManagerReadOnlyAccess
      AssumeRolePolicyDocument: # 信頼ポリシーのプリンシパルにEC2を定義
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SecretManagerReadOnlyAccess # IAMポリシーにシークレットマネージャへの読み取り権限を付与
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetSecretValue'
                Resource: 
                  Fn::ImportValue: !Sub '${SystemName}-${Environment}-Secret-Arn'
      Tags:
      - Key: environment
        Value: !Sub ${Environment}
      - Key: Name
        Value: !Sub ${SystemName}-${Environment}-role-for-ec2  

  InstanceProfile1: # インスタンスプロファイルの作成(EC2へのアタッチに必要)
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref IAMRoleForEC2

  EC2ForRails:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId1  
      InstanceType: !Ref InstanceType1
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 16 
      NetworkInterfaces: 
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: "0"
          GroupSet: !Ref SecurityGroupId1
          SubnetId: !Ref SubnetId1
      Tags:
        - Key: environment
          Value: !Sub ${Environment}
        - Key: Name
          Value: !Sub ${SystemName}-${Environment}-ec2
      KeyName: !Ref KeyName1
      IamInstanceProfile: !Ref InstanceProfile1

Outputs:
  EC2ForRails:
    Description: echo the EC2 instance ID 
    Value: !Ref EC2ForRails
    Export: 
      Name: !Sub ${AWS::StackName}-ec2-instance-id
